name: Deploy

on:
  push:
    branches:
      - main  # Triggers the workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_PEM_FILE }}" | base64 --decode > ~/.ssh/aws_pem_file
          chmod 600 ~/.ssh/aws_pem_file
          ssh-keyscan -H ec2-13-212-183-103.ap-southeast-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh -i ~/.ssh/aws_pem_file ubuntu@ec2-13-212-183-103.ap-southeast-1.compute.amazonaws.com << 'EOF'
            # Source profile files to set up environment variables
            . ~/.profile
            . ~/.bashrc

            # Initialize fnm
            export PATH=$HOME/.fnm:$PATH
            eval "$(fnm env)"

            # Ensure PATH includes the directory for npm and pm2
            export PATH=$PATH:/run/user/1000/fnm_multishells/922886_1719298313686/bin

            cd /var/www/html/nextjs/port-web/
            /run/user/1000/fnm_multishells/922886_1719298313686/bin/pm2 stop 0 || true
            git pull origin main
            /run/user/1000/fnm_multishells/922886_1719298313686/bin/npm install
            /run/user/1000/fnm_multishells/922886_1719298313686/bin/npm run build
            /run/user/1000/fnm_multishells/922886_1719298313686/bin/pm2 reload 0
          EOF
        env:
          AWS_PEM_FILE: ${{ secrets.AWS_PEM_FILE }}
