name: Deploy with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH OY
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_PEM_FILE }}" > ~/.ssh/aws_pem_file
          chmod 600 ~/.ssh/aws_pem_file
          ssh-keyscan -H ec2-18-142-120-147.ap-southeast-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Deploy with Docker Compose
        run: |
          ssh -i ~/.ssh/aws_pem_file ubuntu@ec2-18-142-120-147.ap-southeast-1.compute.amazonaws.com << 'EOF'

            # Ensure Docker is running
            sudo systemctl start docker
            sudo systemctl enable docker

            # Navigate to the app directory
            cd /var/www/html/nextjs/port-web

            # Pull latest changes
            echo "Pulling latest changes..."
            git pull origin main

            # Stop and rebuild with Docker Compose
            echo "Stopping and rebuilding with Docker Compose..."
            sudo docker-compose down
            sudo docker-compose build
            sudo docker-compose up -d 

            # Show logs
            sudo docker-compose logs
          EOF
