name: Deploy with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_PEM_FILE }}" > ~/.ssh/aws_pem_file
          chmod 600 ~/.ssh/aws_pem_file
          ssh-keyscan -H ec2-13-212-183-103.ap-southeast-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Deploy with Docker Compose
        run: |
          ssh -i ~/.ssh/aws_pem_file ubuntu@ec2-13-212-183-103.ap-southeast-1.compute.amazonaws.com << 'EOF'
            cd /var/www/html/nextjs/port-web

            # Pull latest changes
            git pull origin main

            # Stop and rebuild with Docker Compose
            docker compose down
            docker compose up -d --build
          EOF
